### ISSUE TITLE
Double Jump Issue

### ISSUE THREAD

**Issue by Barlender** [Som1Lse/Dish2Macro#1]
With the spring Windows 10 update, bunny hopping still works, double jumping simply doesn't function anymore.

**Comment by Som1Lse** [comment]
Is this also the case, when you aren't running LiveSplit and/or OBS?

**Comment by Barlender** [comment]
No, I tried it without either running, and you're right, it now functions fine. The issue is, of course, that I need them for recording the run, is there any possible work around?

**Comment by Barlender** [comment]
Also I'm running on version 1.3, if that affect anything.

**Comment by Som1Lse** [comment]
Try the newest version and see if it works.
